"""运行时：工具注册、审批、沙箱（M2 扩展）。"""

from agent.runtime.registry import (
    RISK_LEVELS,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    UnknownTool,
    default_registry,
    tool,
)
from agent.runtime.sandbox import (
    CommandFilter,
    DockerExecutor,
    ExecRequest,
    ExecResult,
    Executor,
    ExternalExecutor,
    FakeExecutor,
    FilterVerdict,
    LocalExecutor,
    SandboxProfile,
    build_executor,
    get_executor,
    set_executor,
)
from agent.runtime.approval import (
    Action,
    ApprovalGate,
    ApprovalMode,
    ApprovalUI,
    Decision,
)

__all__ = [
    "RISK_LEVELS",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "UnknownTool",
    "default_registry",
    "tool",
    "CommandFilter",
    "DockerExecutor",
    "ExecRequest",
    "ExecResult",
    "Executor",
    "ExternalExecutor",
    "FakeExecutor",
    "FilterVerdict",
    "LocalExecutor",
    "SandboxProfile",
    "build_executor",
    "get_executor",
    "set_executor",
    "Action",
    "ApprovalGate",
    "ApprovalMode",
    "ApprovalUI",
    "Decision",
]
